# Capture Video from camera
To capture a video, we have to create a VideoCapture object. Its argument can be either the device index or the name of a video file. Device index is just the number to specify which camera. Normally one camera will be connected. So I simply pass 0. You can select the second camera by passing 1 and so on. After that, you can capture frame-by-frame. But at the end, don’t forget to release the capture.

In [1]:
# This code just open the camera for 3 seconds

import cv2, time

# Creating VideoCapture Object
# '0' is to specify that use built-in camera
cap = cv2.VideoCapture(0)

time.sleep(3) # Delay by 3 seconds

# Releasing the camera
cap.release()

In [2]:
# This code just open the camera for 3 seconds and capture the first image

import cv2, time

# Creating VideoCapture Object
# '0' is to specify that use built-in camera
cap = cv2.VideoCapture(0)

# Capturing the frame
check, frame=cap.read()
# check is a bool data type, return true if python is able to read videoCapture object
# frame is a numPy array, it represents the first image that video captures
    
print(check)
print(frame)

time.sleep(3) # Delay by 3 seconds

# Releasing the camera
cap.release()

True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [3]:
# For displaying the first image in a separate window that it captures
cv2.imshow('First Capture Image', frame)

# Wait until a user presses a key
cv2.waitKey(0)

# Destroy all the windows
cv2.destroyAllWindows()

Till now we just capture the first image that appear in front of the camera.

For video we have to capture and display the capture image very fast by using a loop, so that we can see it as a video.

In [4]:
import numpy as np
import cv2

# Creating VideoCapture Object
# '0' is to specify that use built-in camera
cap = cv2.VideoCapture(0)

while(True):
    
    # Capture frame-by-frame
    check, frame = cap.read()
    # check is a bool data type, return true if python is able to read videoCapture object
    # frame is a numPy array, it represents the first image that video captures
    

    # Converting each frame into a gray scale image
    #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)      # If you want gray scale image then use this line

    # Display the resulting frame
    cv2.imshow('Capturing',frame)
    
    # This will generate a new frame after every 1 miliseconds
    key=cv2.waitKey(1) & 0xFF
    
    # Once we enter 'q' the window wwill be destroyed
    if key == ord('q'):
        break

# When everything done, release the capture
# Releasing the camera in some milliseconds
cap.release()

# Destroy all the windows
cv2.destroyAllWindows()

For argument of VideoCapture Object, either give the path to the video file or use numbers. Numbers specify that you will be using the webcam to capture video.

cap.read() returns a bool (True/False). If frame is read correctly, it will be True. So we can check end of the video by checking this return value.

Note : If I have an external cam, I can put '1' to use that. Similarly if I have two external cams and I want to use the cam I can put '3'.

Sometimes, cap may not have initialized the capture. In that case, this code shows error. You can check whether it is initialized or not by the method cap.isOpened(). If it is True, OK. Otherwise open it using cap.open().

You can also access some of the features of this video using cap.get(propId) method where propId is a number from 0 to 18. Each number denotes a property of the video (if it is applicable to that video) and full details can be seen here: Property Identifier. Some of these values can be modified using cap.set(propId, value). Value is the new value you want.

For example, I can check the frame width and height by cap.get(3) and cap.get(4). It gives me 640x480 by default. But I want to modify it to 320x240. Just use ret = cap.set(3,320) and ret = cap.set(4,240).

###########################################################################################################################
# Saving a Video
So we capture a video, process it frame-by-frame and we want to save that video. For images, it is very simple, just use cv2.imwrite(). Here a little more work is required.

This time we create a VideoWriter object. We should specify the output file name (eg: output.avi). Then we should specify the FourCC code (explained below). Then number of frames per second (fps) and frame size should be passed. And last one is isColor flag. If it is True, encoder expect color frame, otherwise it works with grayscale frame.

FourCC is a 4-byte code used to specify the video codec. The list of available codes can be found in fourcc.org. It is platform dependent.

A video codec is an electronic circuit or software that compresses or decompresses digital video. It converts uncompressed video to a compressed format or vice versa.

Following codecs works fine for me.

1. In Fedora: DIVX, XVID, MJPG, X264, WMV1, WMV2. (XVID is more preferable. MJPG results in high size video. X264 gives very small size video)
2. In Windows: DIVX (More to be tested and added)

FourCC code is passed as cv2.VideoWriter_fourcc('M','J','P','G') or cv2.VideoWriter_fourcc(*'MJPG) for MJPG.

Below code capture from a Camera, flip every frame in vertical direction and saves it.

In [5]:
import numpy as np
import cv2

# Creating VideoCapture Object
# '0' is to specify that use built-in camera
cap = cv2.VideoCapture(0)

# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))

while(cap.isOpened()):
    
    # Capture frame-by-frame
    check, frame = cap.read()
    # check is a bool data type, return true if python is able to read videoCapture object
    # frame is a numPy array, it represents the first image that video captures
    
    if check==True:
        frame = cv2.flip(frame,1)

        # write the flipped frame
        out.write(frame)
        
        # Display the resulting frame
        cv2.imshow('Saving',frame)
        
        # This will generate a new frame after every 1 miliseconds
        key=cv2.waitKey(1) & 0xFF

        # Once we enter 'q' the window wwill be destroyed
        if key == ord('q'):
            break
    else:
        break

# Release everything if job is finished
cap.release()
out.release()

# Destroy all the windows
cv2.destroyAllWindows()

# Playing Video from file
It is same as capturing from Camera, just change camera index with video file name. Also while displaying the frame, use appropriate time for cv2.waitKey(). If it is too less, video will be very fast and if it is too high, video will be slow (Well, that is how you can display videos in slow motion). 25 milliseconds will be OK in normal cases.

In [6]:
import numpy as np
import cv2

# Creating VideoCapture Object
# "output.avi" is to specify the file name that we have to play
cap = cv2.VideoCapture("output.avi")

while(cap.isOpened()):
    
    # Capture frame-by-frame
    check, frame = cap.read()
    # check is a bool data type, return true if python is able to read videoCapture object
    # frame is a numPy array, it represents the first image that video captures

    if check==True:
        # Converting each frame into a gray scale image
        #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)      # If you want gray scale image then use this line

        # Display the resulting frame
        cv2.imshow('Playing', frame)

        # This will generate a new frame after every 1 miliseconds
        key=cv2.waitKey(25) & 0xFF

        # Once we enter 'q' the window wwill be destroyed
        if key == ord('q'):
            break
            
    else:
        break

# When everything done, release the capture
# Releasing the camera in some milliseconds
cap.release()

# Destroy all the windows
cv2.destroyAllWindows()